services:
  postgres:
    build:
      context: .
      dockerfile: dockerfile
    image: "postgres-tutorials"
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
       - dbtuto:/data/postgres-tuto
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
    dbtuto:
      external: true

services:
  rabbitmq3:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: 'secret cookie here'
    volumes:
      - ./db-data:/var/lib/rabbitmq
    ports:
      - 15672:15672

